# Generated by Django 4.2.4 on 2024-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_question_answer_remove_question_option1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], default='option1', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='00', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='00', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='00', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='00', max_length=200),
        ),
    ]
