# Generated by Django 5.0.1 on 2024-02-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_option5_question_option6_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
