# Generated by Django 5.0.1 on 2024-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatest', '0002_tquestion_option1_marks_tquestion_option2_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tquestion',
            name='option1_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='option2_marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='option3_marks',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='option4_marks',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='option5_marks',
            field=models.IntegerField(default=4),
        ),
    ]
