# Generated by Django 4.2.4 on 2024-02-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatest', '0004_tquestion_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tquestion',
            name='option1',
            field=models.CharField(default='Almost never', max_length=200),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='option2',
            field=models.CharField(default='Rarely', max_length=200),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='option3',
            field=models.CharField(default='Sometimes', max_length=200),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='option4',
            field=models.CharField(default='Frequently', max_length=200),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='option5',
            field=models.CharField(default='Very Frequently', max_length=200),
        ),
    ]
