# Generated by Django 4.2.4 on 2024-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatest', '0006_result_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tquestion',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
