# Generated by Django 4.2.4 on 2024-02-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatest', '0007_alter_tquestion_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatest.category'),
        ),
    ]
