# Generated by Django 4.2.4 on 2024-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
