# Generated by Django 5.0.1 on 2024-06-01 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0011_result_category_e_result_category_f_and_more'),
        ('student', '0004_alter_student_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='t2Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='result_t2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('category_EI', models.PositiveIntegerField(default=0)),
                ('category_WC', models.PositiveIntegerField(default=0)),
                ('category_EA', models.PositiveIntegerField(default=0)),
                ('category_WI', models.PositiveIntegerField(default=0)),
                ('category_WA', models.PositiveIntegerField(default=0)),
                ('category_EC', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='t2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('option1', models.CharField(default='Usually', max_length=200)),
                ('option2', models.CharField(default='Often', max_length=200)),
                ('option3', models.CharField(default='Sometimes', max_length=200)),
                ('option4', models.CharField(default='Occasionally', max_length=200)),
                ('option5', models.CharField(default='Rarely', max_length=200)),
                ('option6', models.CharField(default='Never', max_length=200)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test2.t2type')),
            ],
        ),
    ]
