# Generated by Django 5.0.1 on 2024-06-01 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_result_category_e_result_category_f_and_more'),
        ('test2', '0002_alter_t2question_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t2question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
    ]
