# Generated by Django 5.0.1 on 2024-02-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0002_rename_question_mquestion'),
        ('quiz', '0010_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='mquestion',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.course'),
        ),
    ]
